addons:
  apt:
    packages:
    - libavformat-dev
    - libavcodec-dev
    - libavutil-dev
    - g++
language:
 - c++
compiler:
 - g++
script:
 - $CXX -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -L/usr/lib -lavformat -lavcodec -lavutil
